CREATE TABLE "customers" (
  "customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "phone" varchar,
  "shipping_address" text NOT NULL
);

CREATE TABLE "products" (
  "product_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_name" varchar NOT NULL,
  "category" varchar,
  "price" decimal(10,2) NOT NULL CHECK ("price" >= 0)
);

CREATE TABLE "inventory" (
  "product_id" integer PRIMARY KEY,
  "quantity_on_hand" integer NOT NULL DEFAULT 0 CHECK ("quantity_on_hand" >= 0)
);

CREATE TABLE "orders" (
  "order_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" integer,
  "order_date" timestamp NOT NULL DEFAULT (now()),
  "total_amount" decimal(10,2),
  "status" varchar
);

CREATE TABLE "order_items" (
  "order_item_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer,
  "product_id" integer,
  "quantity" integer NOT NULL,
  "price_at_purchase" decimal(10,2) NOT NULL
);

COMMENT ON TABLE "products" IS 'Price here is the current catalog price';

COMMENT ON TABLE "order_items" IS 'price_at_purchase captures the price at the moment of sale for historical accuracy';

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;

-- ALTER TABLE "products" ADD FOREIGN KEY ("product_id") REFERENCES "inventory" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "inventory" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;
