-- =============================================
-- INVENTORY AND ORDER MANAGEMENT SYSTEM SCHEMA 
-- =============================================

-- =========================
-- CUSTOMERS
-- =========================
CREATE TABLE "customers" (
  "customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar(255) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "phone" varchar(20),
  "shipping_address" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "is_active" boolean DEFAULT true,

  CONSTRAINT "chk_email_not_empty" CHECK (email ~ '.+@.+\..+'),
  CONSTRAINT "chk_phone_format" CHECK (phone IS NULL OR phone ~ '^\+?[0-9\-\(\) ]{7,}$')
);

-- =========================
-- PRODUCTS
-- =========================
CREATE TABLE "products" (
  "product_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_name" varchar(255) NOT NULL,
  "category" varchar(100) NOT NULL,
  "price" decimal(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "is_active" boolean DEFAULT true,

  CONSTRAINT "chk_price_positive" CHECK ("price" > 0),
  CONSTRAINT "chk_product_name_not_empty" CHECK (product_name <> ''),
  CONSTRAINT "chk_category_not_empty" CHECK (category <> '')
);

-- =========================
-- INVENTORY
-- =========================
CREATE TABLE "inventory" (
  "product_id" integer PRIMARY KEY
    REFERENCES "products"("product_id")
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  "quantity_on_hand" integer NOT NULL DEFAULT 0,
  "reorder_level" integer DEFAULT 10,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "chk_quantity_non_negative" CHECK ("quantity_on_hand" >= 0),
  CONSTRAINT "chk_reorder_level_positive" CHECK ("reorder_level" > 0)
);

-- =========================
-- ORDERS
-- =========================
CREATE TABLE "orders" (
  "order_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" integer NOT NULL,
  "order_date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "total_amount" decimal(10,2) NOT NULL,
  "status" varchar(50) DEFAULT 'Pending',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "chk_order_amount_non_negative"
    CHECK ("total_amount" >= 0),

  CONSTRAINT "chk_status_valid"
    CHECK ("status" IN ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled', 'Refunded')),

  CONSTRAINT "fk_orders_customer_id"
    FOREIGN KEY ("customer_id")
    REFERENCES "customers" ("customer_id")
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

-- =========================
-- ORDER ITEMS
-- =========================
CREATE TABLE "order_items" (
  "order_item_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  "quantity" integer NOT NULL,
  "price_at_purchase" decimal(10,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "chk_quantity_positive"
    CHECK ("quantity" > 0),

  CONSTRAINT "chk_price_at_purchase_non_negative"
    CHECK ("price_at_purchase" >= 0),

  CONSTRAINT "fk_order_items_order_id"
    FOREIGN KEY ("order_id")
    REFERENCES "orders" ("order_id")
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT "fk_order_items_product_id"
    FOREIGN KEY ("product_id")
    REFERENCES "products" ("product_id")
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT "uq_order_product"
    UNIQUE ("order_id", "product_id")
);

-- =========================
-- PAYMENTS
-- =========================
CREATE TABLE "payments" (
  "payment_id" SERIAL PRIMARY KEY,
  "order_id" INT NOT NULL,
  "amount_paid" DECIMAL(10,2) NOT NULL,
  "payment_method" VARCHAR(50),
  "payment_status" VARCHAR(20),
  "payment_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "fk_payments_order_id"
    FOREIGN KEY ("order_id")
    REFERENCES "orders" ("order_id")
    ON DELETE RESTRICT
);

-- =========================
-- AUDIT LOG
-- =========================
CREATE TABLE "audit_log" (
  "audit_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_name" varchar(100) NOT NULL,
  "operation" varchar(20) NOT NULL,
  "record_id" bigint,
  "old_values" jsonb,
  "new_values" jsonb,
  "user_name" varchar(100),
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "chk_operation_valid"
    CHECK ("operation" IN ('INSERT', 'UPDATE', 'DELETE'))
);

-- =========================
-- INDEXES
-- =========================
CREATE INDEX "idx_customers_email" ON "customers" ("email") WHERE "is_active" = true;
CREATE INDEX "idx_products_category" ON "products" ("category") WHERE "is_active" = true;

CREATE INDEX "idx_orders_customer_id" ON "orders" ("customer_id");
CREATE INDEX "idx_orders_order_date" ON "orders" ("order_date");
CREATE INDEX "idx_orders_status" ON "orders" ("status");

CREATE INDEX "idx_order_items_order_id" ON "order_items" ("order_id");
CREATE INDEX "idx_order_items_product_id" ON "order_items" ("product_id");

CREATE INDEX "idx_audit_log_table_created"
ON "audit_log" ("table_name", "created_at");

-- =========================
-- COMMENTS
-- =========================

COMMENT ON TABLE "products" IS 'Price here is the current catalog price';
COMMENT ON TABLE "order_items" IS 'price_at_purchase captures the price at the moment of sale for historical accuracy';
COMMENT ON COLUMN "inventory"."reorder_level" IS 'Threshold for low stock alerts';
COMMENT ON COLUMN "orders"."status" IS 'Allowed values: Pending, Processing, Shipped, Delivered, Cancelled, Refunded';